# Generated by Django 5.1.6 on 2025-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_profile", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_img",
            field=models.ImageField(blank=True, default="avatar_1.png", upload_to=""),
        ),
    ]
