# Generated by Django 5.1.6 on 2025-02-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_profile", "0003_user_user_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_img",
        ),
    ]
