# Generated by Django 5.1.6 on 2025-02-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_profile", "0004_remove_user_user_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_img",
            field=models.ImageField(blank=True, default="avatar_3.png", upload_to=""),
        ),
    ]
